version: '3'
services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: framgia
      POSTGRES_PASSWORD: 123123
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    container_name: web_app
    depends_on:
      - "postgres"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/your-danang-bus
      - ./scripts:/scripts
    ports:
      - "3000:3000"
    command: /scripts/start_rails.sh

volumes:
  postgres:
